#Работа с модулем Numpy

In [1]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [2]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list)
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [3]:
z = np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [4]:
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [5]:
ones = np.ones(12)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [6]:
ones = ones.reshape(3, 4)
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на (-99)

In [17]:
Z = np.array([list(range(1, 21))]).reshape(4, 5)
print(Z)
Z[2][3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [8]:
first = np.random.randint(-10, 11, size=15)
print(first)
second = first[::-1]
print(second)

[ -8   7  -7  -8  -3   0  -9  -8   5   8  -4 -10   6 -10   3]
[  3 -10   6 -10  -4   8   5  -8  -9   0  -3  -8  -7   7  -8]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [9]:
first = np.random.randint(low=-15, high=16, size=(5, 5))
print(first)
first[first < 0] = first[first < 0] ** 2
print(first)

[[  5   9  13  13 -11]
 [ 14 -13  13 -10  -8]
 [ -8 -15  -2  -4 -11]
 [ 15  -1  15   7   9]
 [ 12  -1   7  -3 -14]]
[[  5   9  13  13 121]
 [ 14 169  13 100  64]
 [ 64 225   4  16 121]
 [ 15   1  15   7   9]
 [ 12   1   7   9 196]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [10]:
first = np.random.randint(low=-15, high=16, size=(3, 5))
print(first)
max_val = np.max(first)
min_val = np.min(first)
col_means = np.mean(first, axis=0)
row_means = np.mean(first, axis=1)
print(max_val)
print(min_val)
print(col_means)
print(row_means)


[[-15   5 -15 -10  11]
 [  0 -10  15  -6  -2]
 [ 12   9 -15  10  15]]
15
-15
[-1.          1.33333333 -5.         -2.          8.        ]
[-4.8 -0.6  6.2]


10. Задание
- даны две матрицы
- убедитесь, что их можно перемножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [14]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print("количество столбцов первой матрицы не совпадает с количеством строк второй матрицы")

[[ 10 -18  51]
 [ 37 -81 -47]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоном от 2 до 12
- заполните все элементы ниже главной диагонали нулями

In [19]:
mask = np.tril_indices(5, -1)
matrix = np.random.uniform(2, 13, (5, 5))
matrix[mask] = 0
print(matrix)

[[ 4.78544306  6.17676264  3.82014598  5.55883146  8.31453998]
 [ 0.          5.45241589  7.33248216  9.3652841   8.10343728]
 [ 0.          0.         12.15005668 11.80449559 10.45649604]
 [ 0.          0.          0.          9.28836454  5.20641087]
 [ 0.          0.          0.          0.          6.56874871]]


12. Задание
- создайте матрицу 5 на 5, заполненную нормальным распределением с параметрами: среднее 10 и стандартное отклонение 2
- заполните все элементы на главной диагонали нулями

In [21]:
mask = np.eye(5, dtype=bool)
matrix = np.random.normal(loc=10, scale=2, size=(5, 5))
matrix[mask] = 0
print(matrix)

[[ 0.         10.56188536  8.5745018  11.30847791 11.81535201]
 [10.36527428  0.          5.26144715  7.86545316 11.65774646]
 [10.5823039  11.1303892   0.          9.4721697  12.25183497]
 [ 8.87899038  6.71731205 10.57647389  0.          9.61769863]
 [11.87828579 10.06854744  7.88661729 11.0060944   0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [24]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
equal

[0 1 0 0 1]
[0 1 1 1 1]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [26]:
r, c = np.random.randint(3, 8), np.random.randint(2, 13)
a = np.random.randint(10, 100, size=(r, c))
print(a)
N = np.random.randint(1, a.size // 2 + 1)
print(N)
linear_indices = np.random.choice(a.size, size=N, replace=False)
r, c = np.unravel_index(linear_indices, a.shape)
sample = a[r, c]
print(sample)

[[11 98 31 24 11 42 61 80 42]
 [10 37 85 93 97 13 22 89 65]
 [44 13 83 19 86 87 80 86 93]
 [62 57 92 42 51 34 81 10 55]
 [20 33 92 42 56 65 45 89 55]]
19
[45 62 89 87 83 24 42 65 31 85 33 65 10 20 97 10 34 92 57]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [31]:
a = np.array([1, np.nan, np.inf], float)
print(np.isnan(a).any())
print(np.isinf(a).any())
a[np.isnan(a) | np.isinf(a)] = 0
print(a)

True
True
[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [69]:
axis = np.random.randint(1, 6)
print(axis)
matrix = np.random.rand(*[2] * axis)
print(matrix.ndim)
print(matrix)

3
3
[[[0.22304982 0.65178488]
  [0.36939179 0.10421054]]

 [[0.16925247 0.65501376]
  [0.28103265 0.99672218]]]


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, стандартное отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [58]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = np.argmax(matrix, axis=1)
print(indexes)
print(np.max(matrix, axis=1))

[[56.23454729 47.64352113 34.6701432 ]
 [58.82174879 37.55615028 39.6589924 ]
 [60.70801813 50.54747119 48.99302337]
 [30.018683   45.66998297 69.40442987]
 [53.12170254 42.33053139 36.95182467]
 [47.93886225 45.68666324 37.29329114]
 [33.14102501 54.42229713 55.06635149]
 [48.56821877 48.46375724 39.59636652]
 [40.24983501 35.94464754 45.44359828]
 [59.76034761 53.17019788 48.19733005]]
[0 0 0 2 0 0 2 0 2 0]
[56.23454729 58.82174879 60.70801813 69.40442987 53.12170254 47.93886225
 55.06635149 48.56821877 45.44359828 59.76034761]


18. Задача на теорию вероятности. Реализовать решение методом Монте-Карло

1. Бросаем два игральных кубика: красный и синий. Определите вероятность того, что цифры на красном и синем кубиках совпадут.
2. В этом же эксперименте с кубиками нужно найти наиболее вероятную сумму цифр на кубиках.
3. Наудачу выбирается одно число от 1 до 20. Считая все числа равновозможными, определите вероятность того, что выбранное число:
* чётно;
* делится на 3;
* делится и на 2, и на 3;
* не делится ни на 2, ни на 3;
* имеет сумму цифр 9;
* имеет сумму цифр, делящуюся на 3.

In [62]:
N = 1_000_000
red = np.random.randint(1, 7, size=N)
blue = np.random.randint(1, 7, size=N)
matching_dice = (red == blue)
prob_match = np.mean(matching_dice)
print(f"Вероятность совпадения цифр (Монте-Карло): {prob_match:.4f} (Теория: {1/6:.4f})")

sums = red + blue
values, counts = np.unique(sums, return_counts=True)
most_probable_sum = values[np.argmax(counts)]
print(f"Наиболее вероятная сумма кубиков: {most_probable_sum} (Теория: 7)")

numbers = np.random.randint(1, 21, size=N)
prob_even = np.mean(numbers % 2 == 0)
print(f"Чётное: {prob_even:.4f} (Теория: {10/20:.2f})")

prob_div3 = np.mean(numbers % 3 == 0)
print(f"Делится на 3: {prob_div3:.4f} (Теория: {6/20:.2f})")

prob_div2_and_3 = np.mean((numbers % 2 == 0) & (numbers % 3 == 0))
print(f"Делится на 2 и на 3: {prob_div2_and_3:.4f} (Теория: {3/20:.2f})")

prob_neither = np.mean((numbers % 2 != 0) & (numbers % 3 != 0))
print(f"Не делится ни на 2, ни на 3: {prob_neither:.4f} (Теория: {7/20:.2f})")

digit_sums = (numbers // 10) + (numbers % 10)

prob_sum9 = np.mean(digit_sums == 9)
print(f"Сумма цифр равна 9: {prob_sum9:.4f} (Теория: {2/20:.2f})")

prob_sum_div3 = np.mean(digit_sums % 3 == 0)
print(f"Сумма цифр делится на 3: {prob_sum_div3:.4f} (Теория: {6/20:.2f})")

Вероятность совпадения цифр (Монте-Карло): 0.1669 (Теория: 0.1667)
Наиболее вероятная сумма кубиков: 7 (Теория: 7)
Чётное: 0.5012 (Теория: 0.50)
Делится на 3: 0.2992 (Теория: 0.30)
Делится на 2 и на 3: 0.1504 (Теория: 0.15)
Не делится ни на 2, ни на 3: 0.3500 (Теория: 0.35)
Сумма цифр равна 9: 0.0993 (Теория: 0.10)
Сумма цифр делится на 3: 0.2992 (Теория: 0.30)
