#Работа с модулем Numpy

In [1]:
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [2]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list)
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [3]:
z = np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [4]:
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [5]:
ones = np.ones(12)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [6]:
ones = ones.reshape(3, 4)
ones.shape

(3, 4)

6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на (-99)

In [7]:
Z = np.array([list(range(1, 21))]).reshape(4, 5)
print(Z)
Z[2][3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [8]:
first = np.random.randint(-10, 11, size=15)
print(first)
second = first[::-1]
print(second)

[ 0 10  0  4  7  7  1 -6 -6  0  6 -4  7 -5  0]
[ 0 -5  7 -4  6  0 -6 -6  1  7  7  4  0 10  0]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [9]:
first = np.random.randint(low=-15, high=16, size=(5, 5))
print(first)
first[first < 0] = first[first < 0] ** 2
print(first)

[[-10  12  10  15   4]
 [ -6   3   4  -5   6]
 [  3  -5   9  -9  11]
 [  0   7  -7 -12  10]
 [ -4  -5   7 -10   2]]
[[100  12  10  15   4]
 [ 36   3   4  25   6]
 [  3  25   9  81  11]
 [  0   7  49 144  10]
 [ 16  25   7 100   2]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [10]:
first = np.random.randint(low=-15, high=16, size=(3, 5))
print(first)
max_val = np.max(first)
min_val = np.min(first)
col_means = np.mean(first, axis=0)
row_means = np.mean(first, axis=1)
print(max_val)
print(min_val)
print(col_means)
print(row_means)


[[ -4  11  -8  12   3]
 [ 15   9   1  -8 -12]
 [  6   5  -4  12   3]]
15
-12
[ 5.66666667  8.33333333 -3.66666667  5.33333333 -2.        ]
[2.8 1.  4.4]


10. Задание
- даны две матрицы
- убедитесь, что их можно перемножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [11]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print("количество столбцов первой матрицы не совпадает с количеством строк второй матрицы")

количество столбцов первой матрицы не совпадает с количеством строк второй матрицы


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоном от 2 до 12
- заполните все элементы ниже главной диагонали нулями

In [12]:
mask = np.tril_indices(5, -1)
matrix = np.random.uniform(2, 13, (5, 5))
matrix[mask] = 0
print(matrix)

[[ 4.23024874  5.2995937   7.4809552   4.55422718  4.70127412]
 [ 0.          7.35026827 10.2585676   3.62977808  8.71900213]
 [ 0.          0.          9.46733845  6.37450532 10.16587156]
 [ 0.          0.          0.          8.27212622  5.75199101]
 [ 0.          0.          0.          0.          7.61303226]]


12. Задание
- создайте матрицу 5 на 5, заполненную нормальным распределением с параметрами: среднее 10 и стандартное отклонение 2
- заполните все элементы на главной диагонали нулями

In [13]:
mask = np.eye(5, dtype=bool)
matrix = np.random.normal(loc=10, scale=2, size=(5, 5))
matrix[mask] = 0
print(matrix)

[[ 0.         12.31936983  9.96514649  9.15989302 11.14770119]
 [11.68815066  0.         11.70365334  9.25056596 12.96101776]
 [ 9.4855297  10.57727833  0.          8.92027991  9.33147043]
 [ 5.81561875  4.90440545  9.85245444  0.         12.76027286]
 [11.98321758 12.29680254  9.89133402  7.8342006   0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [14]:
a = np.random.randint(0,2,5)
print(a)
b = np.random.randint(0,2,5)
print(b)
equal = np.array_equal(a, b)
equal

[1 1 0 0 0]
[1 1 0 0 1]


False

14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [15]:
r, c = np.random.randint(3, 8), np.random.randint(2, 13)
a = np.random.randint(10, 100, size=(r, c))
print(a)
N = np.random.randint(1, a.size // 2 + 1)
print(N)
linear_indices = np.random.choice(a.size, size=N, replace=False)
r, c = np.unravel_index(linear_indices, a.shape)
sample = a[r, c]
print(sample)

[[72 60 99]
 [26 34 83]
 [75 20 63]
 [68 35 66]]
6
[26 75 60 99 83 66]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [16]:
a = np.array([1, np.nan, np.inf], float)
print(np.isnan(a).any())
print(np.isinf(a).any())
a[np.isnan(a) | np.isinf(a)] = 0
print(a)

True
True
[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [17]:
axis = np.random.randint(1, 6)
print(axis)
matrix = np.random.rand(*[2] * axis)
print(matrix.ndim)
print(matrix)

1
1
[0.54044363 0.05459773]


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, стандартное отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [18]:
matrix = np.random.normal(50, 10, (10,3))
print(matrix)
indexes = np.argmax(matrix, axis=1)
print(indexes)
print(np.max(matrix, axis=1))

[[50.46258879 57.43221197 49.05199143]
 [38.424611   49.06489828 58.78760368]
 [66.88925107 40.28546361 49.42049643]
 [35.01126655 57.49336018 65.44988008]
 [38.04268848 43.22776849 64.59827449]
 [46.6983269  55.39058435 57.91281241]
 [55.15894982 54.32650351 42.13329584]
 [65.8432572  44.404465   65.90135482]
 [53.80741898 56.1474397  53.92370735]
 [36.94672992 56.4199817  49.96574916]]
[1 2 0 2 2 2 0 2 1 1]
[57.43221197 58.78760368 66.88925107 65.44988008 64.59827449 57.91281241
 55.15894982 65.90135482 56.1474397  56.4199817 ]


18. Задача на теорию вероятности. Реализовать решение методом Монте-Карло

1. Бросаем два игральных кубика: красный и синий. Определите вероятность того, что цифры на красном и синем кубиках совпадут.
2. В этом же эксперименте с кубиками нужно найти наиболее вероятную сумму цифр на кубиках.
3. Наудачу выбирается одно число от 1 до 20. Считая все числа равновозможными, определите вероятность того, что выбранное число:
* чётно;
* делится на 3;
* делится и на 2, и на 3;
* не делится ни на 2, ни на 3;
* имеет сумму цифр 9;
* имеет сумму цифр, делящуюся на 3.

In [19]:
N = 1_000_000
red = np.random.randint(1, 7, size=N)
blue = np.random.randint(1, 7, size=N)
matching = (red == blue)
prob = np.mean(matching)
print(f"Вероятность совпадения цифр (Монте-Карло): {prob}")

sums = red + blue
values, counts = np.unique(sums, return_counts=True)
most_probable_sum = values[np.argmax(counts)]
print(f"Наиболее вероятная сумма кубиков: {most_probable_sum}")

numbers = np.random.randint(1, 21, size=N)
prob_even = np.mean(numbers % 2 == 0)
print(f"Чётное: {prob_even}")

prob_div3 = np.mean(numbers % 3 == 0)
print(f"Делится на 3: {prob_div3:.4f}")

prob_div2_and_3 = np.mean((numbers % 2 == 0) & (numbers % 3 == 0))
print(f"Делится на 2 и на 3: {prob_div2_and_3}")

prob_neither = np.mean((numbers % 2 != 0) & (numbers % 3 != 0))
print(f"Не делится ни на 2, ни на 3: {prob_neither}")

digit_sums = (numbers // 10) + (numbers % 10)

prob_sum9 = np.mean(digit_sums == 9)
print(f"Сумма цифр равна 9: {prob_sum9}")

prob_sum_div3 = np.mean(digit_sums % 3 == 0)
print(f"Сумма цифр делится на 3: {prob_sum_div3}")

Вероятность совпадения цифр (Монте-Карло): 0.166667
Наиболее вероятная сумма кубиков: 7
Чётное: 0.500371
Делится на 3: 0.3009
Делится на 2 и на 3: 0.150302
Не делится ни на 2, ни на 3: 0.349025
Сумма цифр равна 9: 0.100652
Сумма цифр делится на 3: 0.300906
